"use client";

import { Download } from "lucide-react";
import type { GateVerdict, PrepReport } from "@data/lib/prep/types";

function reportHtml(report: PrepReport, score: number, gate: GateVerdict, profileName: string, applied: Set<string>): string {
  const row = (k: string, v: string) => `<tr><td>${k}</td><td>${v}</td></tr>`;
  const checks = report.checks
    .map((c) => {
      const resolved = c.fix && applied.has(c.fix.id);
      const state = resolved ? "Resolved" : c.level;
      return `<tr><td>${c.name}</td><td>${c.guideline}</td><td class="lvl ${resolved ? "ok" : c.level}">${state}</td><td>${c.detail}</td></tr>`;
    })
    .join("");
  const date = new Date().toISOString().slice(0, 16).replace("T", " ");
  return `<!doctype html><html><head><meta charset="utf-8"><title>Data Readiness Report — ${report.fileName}</title>
<style>
body{font-family:'Public Sans',system-ui,sans-serif;color:#152433;max-width:840px;margin:32px auto;padding:0 20px;background:#f6f7f8}
h1{font-size:22px;margin:0 0 4px}.sub{color:#5f6f81;font-size:13px;margin:0 0 20px}
.card{background:#fff;border:1px solid #e4e7eb;border-radius:12px;padding:16px;margin-bottom:16px}
.score{font-size:40px;font-weight:600;letter-spacing:-.02em}.gate{display:inline-block;padding:3px 10px;border-radius:6px;font-size:13px;font-weight:600}
.Approved,.ok{background:#ecfdf5;color:#15803d}.Conditional{background:#fffbeb;color:#b45309}.Hold{background:#fff7ed;color:#c2410c}.Rejected,.critical{background:#fef2f2;color:#b91c1c}
table{width:100%;border-collapse:collapse;font-size:13px}td,th{text-align:left;padding:6px 8px;border-bottom:1px solid #eef1f4}th{color:#5f6f81;font-size:11px;text-transform:uppercase;letter-spacing:.04em}
.lvl{font-weight:600}.healthy{color:#16a34a}.watch{color:#d97706}.risk{color:#ea580c}
.foot{color:#7c8a9a;font-size:11px;margin-top:20px}
</style></head><body>
<h1>Data Readiness Report</h1>
<p class="sub">${report.fileName} · ${report.ext.toUpperCase()} · profile: ${profileName} · generated ${date}</p>
<div class="card"><div class="score">${score}<span style="font-size:16px;color:#7c8a9a"> / 100</span></div>
<div style="margin-top:8px"><span class="gate ${gate.gate}">${gate.gate}</span> — ${gate.verdict}</div>
<p style="color:#46586b;font-size:14px;margin:10px 0 0">${gate.summary}</p></div>
<div class="card"><h3 style="margin:0 0 8px;font-size:15px">Profile</h3>
<table><tr><td>Rules profile</td><td>${profileName}</td></tr>${row("Approved chunks", report.chunk.count.toLocaleString())}${row("Est. embedding tokens", report.chunk.estTokens.toLocaleString())}</table></div>
<div class="card"><h3 style="margin:0 0 8px;font-size:15px">Guideline checks</h3>
<table><tr><th>Check</th><th>Guideline</th><th>Status</th><th>Detail</th></tr>${checks}</table></div>
<p class="foot">Generated by Data Lab · upstream prep for the RAG Evaluator · all values for demonstration.</p>
</body></html>`;
}

export function ExportReport({
  report,
  score,
  gate,
  profileName,
  applied,
}: {
  report: PrepReport;
  score: number;
  gate: GateVerdict;
  profileName: string;
  applied: Set<string>;
}) {
  const download = () => {
    const html = reportHtml(report, score, gate, profileName, applied);
    const blob = new Blob([html], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `data-readiness-${report.fileName.replace(/\.[^.]+$/, "")}.html`;
    a.click();
    URL.revokeObjectURL(url);
  };
  return (
    <button
      onClick={download}
      className="inline-flex items-center gap-1.5 rounded-lg border border-line bg-white px-3 py-1.5 text-xs font-medium text-slatey-200 transition-colors hover:border-primary/40 hover:text-primary"
    >
      <Download className="h-3.5 w-3.5" />
      Export readiness report
    </button>
  );
}
