'use client';
import { useEffect, useState } from 'react';
import { api } from '@gov/lib/api';
import type { EvidenceReport } from '@gov/lib/types';
import { StatusBadge } from '@gov/components/shared/Badge';
import { LoadingSpinner } from '@gov/components/shared/LoadingSpinner';
import { formatDate } from '@gov/lib/utils';
import { FileText, Download, Plus } from 'lucide-react';

export default function EvidenceCenter() {
  const [reports, setReports] = useState<EvidenceReport[]>([]);
  const [selected, setSelected] = useState<EvidenceReport | null>(null);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [showForm, setShowForm] = useState(false);
  const [form, setForm] = useState({ title: 'AI Governance Audit Evidence', generated_by: 'ai-governance@corp.example.com', period_start: '2026-01-01', period_end: '2026-06-30' });

  useEffect(() => {
    api.evidence.list().then(d => { setReports(d); if (d.length) setSelected(d[0]); }).finally(() => setLoading(false));
  }, []);

  const generate = async (e: React.FormEvent) => {
    e.preventDefault();
    setGenerating(true);
    try {
      const r = await api.evidence.create({ ...form, period_start: new Date(form.period_start).toISOString(), period_end: new Date(form.period_end).toISOString(), sections: ['risk_posture', 'policies', 'runtime', 'evals', 'human_review', 'audit'] });
      setReports(prev => [r, ...prev]);
      setSelected(r);
      setShowForm(false);
    } finally { setGenerating(false); }
  };

  if (loading) return <LoadingSpinner />;

  return (
    <div className="p-8 space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <p className="text-xs font-semibold text-slate-400 uppercase tracking-widest">Compliance</p>
          <h2 className="text-2xl font-bold text-slate-900 mt-1">Audit Evidence Center</h2>
        </div>
        <button onClick={() => setShowForm(!showForm)} className="flex items-center gap-2 bg-blue-600 text-white px-4 py-2 rounded-md text-sm font-medium hover:bg-blue-700">
          <Plus size={16} /> Generate Report
        </button>
      </div>

      {showForm && (
        <form onSubmit={generate} className="bg-white border border-slate-200 rounded-xl p-5 space-y-4">
          <h3 className="text-sm font-semibold text-slate-700">New Evidence Report</h3>
          <div className="grid grid-cols-2 gap-4">
            {[['title', 'Report Title'], ['generated_by', 'Generated By (email)'], ['period_start', 'Period Start'], ['period_end', 'Period End']].map(([k, label]) => (
              <div key={k}>
                <label className="block text-xs font-semibold text-slate-600 mb-1">{label}</label>
                <input type={k.includes('period') ? 'date' : 'text'} className="w-full border border-slate-200 rounded px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500" value={(form as Record<string, string>)[k]} onChange={e => setForm(f => ({ ...f, [k]: e.target.value }))} required />
              </div>
            ))}
          </div>
          <div className="flex gap-3">
            <button type="submit" disabled={generating} className="bg-blue-600 text-white px-5 py-2 rounded text-sm font-medium hover:bg-blue-700 disabled:opacity-50">{generating ? 'Generating…' : 'Generate'}</button>
            <button type="button" onClick={() => setShowForm(false)} className="text-sm text-slate-500 px-3 py-2">Cancel</button>
          </div>
        </form>
      )}

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="bg-white border border-slate-200 rounded-xl overflow-hidden">
          <div className="px-4 py-3 border-b border-slate-100 bg-slate-50 text-xs font-semibold text-slate-500 uppercase">Reports</div>
          <div className="divide-y divide-slate-100">
            {reports.map(r => (
              <button key={r.id} onClick={() => setSelected(r)} className={`w-full text-left px-4 py-3 hover:bg-slate-50 ${selected?.id === r.id ? 'bg-blue-50 border-l-2 border-blue-500' : ''}`}>
                <div className="flex items-center gap-2 mb-1">
                  <FileText size={14} className="text-slate-400" />
                  <span className="text-sm font-medium text-slate-800 flex-1 text-left">{r.title}</span>
                </div>
                <div className="flex items-center justify-between">
                  <StatusBadge status={r.status} />
                  <span className="text-xs text-slate-400">{formatDate(r.created_at)}</span>
                </div>
                <div className="mt-1">
                  <div className="flex items-center justify-between text-xs text-slate-400 mb-0.5">
                    <span>Completeness</span><span>{r.completeness_score}%</span>
                  </div>
                  <div className="bg-slate-100 rounded-full h-1.5">
                    <div className="h-1.5 rounded-full bg-blue-500" style={{ width: `${r.completeness_score}%` }} />
                  </div>
                </div>
              </button>
            ))}
          </div>
        </div>

        {selected && (
          <div className="lg:col-span-2 space-y-4">
            <div className="bg-white border border-slate-200 rounded-xl p-5">
              <div className="flex items-start justify-between mb-3">
                <div>
                  <h3 className="font-semibold text-slate-900">{selected.title}</h3>
                  <p className="text-xs text-slate-400 mt-0.5">Period: {formatDate(selected.period_start)} to {formatDate(selected.period_end)}</p>
                </div>
                <a href={api.evidence.downloadUrl(selected.id)} download className="flex items-center gap-1.5 text-xs border border-slate-200 px-3 py-1.5 rounded text-slate-600 hover:bg-slate-50">
                  <Download size={13} /> Download .md
                </a>
              </div>
              <div className="grid grid-cols-5 gap-3 mb-4">
                {[['Use Cases', selected.use_case_count], ['Policies', selected.policy_count], ['Events', selected.prompt_event_count], ['Eval Runs', selected.eval_run_count], ['Reviews', selected.review_item_count]].map(([k, v]) => (
                  <div key={k} className="text-center bg-slate-50 rounded p-2">
                    <p className="text-lg font-bold text-slate-800">{v}</p>
                    <p className="text-xs text-slate-500">{k}</p>
                  </div>
                ))}
              </div>
            </div>
            <div className="bg-white border border-slate-200 rounded-xl p-5">
              <p className="text-xs font-semibold text-slate-500 uppercase mb-3">Report Preview</p>
              <pre className="text-xs text-slate-700 whitespace-pre-wrap font-mono bg-slate-50 rounded p-4 max-h-96 overflow-y-auto">{selected.content_markdown}</pre>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
